#!/usr/bin/env python3
"""Bakes the weather icons in src/ into components/icons/ as a Font, one
glyph per icon at a Private Use Area codepoint, so they're drawn with the
same Canvas::drawText as text (see the dev plan's text rendering notes).

    ../font_subset/.venv/bin/python bake_icons.py

The sources were cut from the Raspberry Pi version's background images
(ePaper-Google-Calendar, pic/Calendar1-5.bmp): every weather icon from the
same 101x80 box, so drawing any of them with the pen at the box's
bottom-left corner puts it where the Pi layout had it. Light pixels (white
and the raindrop's yellow) become ink.
"""
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent.parent / "components" / "icons"
INK_THRESHOLD = 128  # luminance

# (source, codepoint, C++ name). Codepoints are part of the firmware's
# interface (icons.hpp), so only ever append.
ICONS = [
    ("sunny.png", 0xE000, "kSunny"),
    ("partly_cloudy.png", 0xE001, "kPartlyCloudy"),
    ("cloudy.png", 0xE002, "kCloudy"),
    ("windy.png", 0xE003, "kWindy"),
    ("rainy.png", 0xE004, "kRainy"),
    ("raindrop.png", 0xE005, "kRaindrop"),
    ("wifi_off.png", 0xE006, "kWifiOff"),  # drawn by draw_status_icons.py
]


def bake(path, codepoint):
    """Glyph tuple with the pen at the source image's bottom-left corner."""
    img = Image.open(path).convert("L")
    ink = img.point(lambda v: 255 if v >= INK_THRESHOLD else 0)
    box = ink.getbbox()
    ink = ink.crop(box)
    width, height = ink.size
    row_bytes = (width + 7) // 8
    rows = bytearray()
    pixels = ink.load()
    for y in range(height):
        row = bytearray(row_bytes)
        for x in range(width):
            if pixels[x, y]:
                row[x // 8] |= 0x80 >> (x % 8)
        rows += row
    bearing_x = box[0]
    bearing_y = img.height - box[1]
    advance = img.width
    return codepoint, width, height, bearing_x, bearing_y, advance, bytes(rows), img.height


def utf8_escape(codepoint):
    return "".join(f"\\x{b:02X}" for b in chr(codepoint).encode("utf-8"))


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    glyphs = [bake(HERE / "src" / name, cp) for name, cp, _ in ICONS]
    ascent = max(g[7] for g in glyphs)

    lines = [
        "// Generated by tools/icons/bake_icons.py -- do not edit.",
        "",
        '#include "icons.hpp"',
        "",
        "namespace {",
        "",
        "constexpr uint8_t kBitmaps[] = {",
    ]
    blob = bytearray()
    offsets = []
    for g in glyphs:
        offsets.append(len(blob))
        blob += g[6]
    for i in range(0, len(blob), 20):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i : i + 20]) + ",")
    lines += ["};", "", "constexpr Glyph kGlyphs[] = {"]
    for (name, _, _), g, offset in zip(ICONS, glyphs, offsets):
        cp, width, height, bx, by, advance = g[:6]
        lines.append(f"    {{0x{cp:04x}, {offset}, {width}, {height}, {bx}, {by}, {advance}}},  // {name}")
    lines += [
        "};",
        "",
        "}  // namespace",
        "",
        f"constexpr Font kWeatherIcons{{kGlyphs, kBitmaps, {ascent}, {ascent}}};",
        "",
    ]
    (OUT_DIR / "weather_icons.cpp").write_text("\n".join(lines), encoding="utf-8")

    header = [
        "#pragma once",
        "",
        "// Generated by tools/icons/bake_icons.py -- do not edit.",
        "",
        '#include "font.hpp"',
        "",
        "// Weather and status icons as glyphs. Draw one with drawText; the pen",
        "// position is the icon box's bottom-left corner (weather icons share a",
        "// 101x80 box, status icons a 24x24 one).",
        "extern const Font kWeatherIcons;",
        "",
        "namespace icons {",
    ]
    for _, cp, symbol in ICONS:
        header.append(f'inline constexpr const char* {symbol} = "{utf8_escape(cp)}";  // U+{cp:04X}')
    header += ["}  // namespace icons", ""]
    (OUT_DIR / "icons.hpp").write_text("\n".join(header), encoding="utf-8")

    (OUT_DIR / "CMakeLists.txt").write_text(
        'idf_component_register(SRCS "weather_icons.cpp"\n'
        '                    INCLUDE_DIRS "."\n'
        "                    REQUIRES canvas)\n",
        encoding="utf-8",
    )
    print(f"{len(glyphs)} icons, {len(blob)} bitmap bytes")


if __name__ == "__main__":
    main()
