#!/usr/bin/env python3
"""Bakes the built-in privacy-mode photos into components/photos/: each one
cropped to the photo frame and dithered twice -- to 1bpp (a Bitmap) and to
four gray levels for panels with a 4-gray mode (a GrayBitmap).

    ../font_subset/.venv/bin/python bake_photos.py

Sources are public-domain prints from Wikimedia Commons, downloaded into
.cache/ (gitignored) on first run with their SHA-256 pinned. Uploaded
photos go through the same steps in the browser (setup page), so keep the
two in step: fit-crop, autocontrast (1% cutoff), Atkinson dithering.
"""
import hashlib
import math
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageOps

HERE = Path(__file__).resolve().parent
CACHE = HERE / ".cache"
OUT_DIR = HERE.parent.parent / "components" / "photos"

# Must match photos.hpp / the calendar view's photo frame.
WIDTH, HEIGHT = 730, 280


@dataclass
class Photo:
    name: str  # C++ symbol suffix
    url: str
    sha256: str
    center_y: float  # vertical crop position, 0 = top, 1 = bottom
    credit: str


PHOTOS = [
    Photo(
        "GreatWave",
        "https://upload.wikimedia.org/wikipedia/commons/a/a5/Tsunami_by_hokusai_19th_century.jpg",
        "30c170260de393f51bd592adacc6f0714b60f157c09744e9c5b6d46e6a613718",
        0.55,
        "Katsushika Hokusai, The Great Wave off Kanagawa (c. 1831), public domain",
    ),
    Photo(
        "RedFuji",
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Red_Fuji_southern_wind_clear_morning.jpg",
        "6266cbb436f958b3197f6a048c3a738a7353eb4d6f37702970ee9feb689f47cd",
        0.42,
        "Katsushika Hokusai, Fine Wind, Clear Morning (c. 1831), public domain",
    ),
]


def fetch(photo):
    path = CACHE / Path(photo.url).name
    if not path.exists():
        CACHE.mkdir(exist_ok=True)
        print(f"downloading {photo.url}")
        request = urllib.request.Request(photo.url, headers={"User-Agent": "GlanceFirmware/1.0 (personal project)"})
        with urllib.request.urlopen(request) as response:
            path.write_bytes(response.read())
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != photo.sha256:
        raise SystemExit(f"{path.name} changed upstream (sha256 {digest}); review, then update the pin")
    return path


def atkinson_levels(img, levels):
    """Each pixel quantized to 0..levels-1 (0 = black) by Atkinson
    dithering: 6/8 of the error spreads to nearby pixels, the rest is
    dropped, which keeps highlights and shadows clean on e-paper."""
    w, h = img.size
    px = [float(v) for v in img.tobytes()]
    step = 255.0 / (levels - 1)
    out = []
    for y in range(h):
        for x in range(w):
            i = y * w + x
            old = px[i]
            # floor(x + 0.5), not round(): matches JavaScript's Math.round, for the upload page.
            level = min(levels - 1, max(0, math.floor(old / step + 0.5)))
            out.append(level)
            err = (old - level * step) / 8
            for dx, dy in ((1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)):
                xx, yy = x + dx, y + dy
                if 0 <= xx < w and yy < h:
                    px[yy * w + xx] += err
    return out


def pack(levels, w, h, bits):
    """Rows of `bits`-per-pixel values, MSB first, each row padded to a byte."""
    per_byte = 8 // bits
    rows = bytearray()
    for y in range(h):
        row = bytearray((w + per_byte - 1) // per_byte)
        for x in range(w):
            row[x // per_byte] |= levels[y * w + x] << (8 - bits - bits * (x % per_byte))
        rows += row
    return bytes(rows)


def bake(photo):
    """(1bpp bits, 2bpp bits) for the photo."""
    img = Image.open(fetch(photo)).convert("L")
    img = ImageOps.fit(img, (WIDTH, HEIGHT), Image.LANCZOS, centering=(0.5, photo.center_y))
    img = ImageOps.autocontrast(img, cutoff=1)
    return pack(atkinson_levels(img, 2), WIDTH, HEIGHT, 1), pack(atkinson_levels(img, 4), WIDTH, HEIGHT, 2)


def emit_array(lines, name, bits):
    lines.append(f"constexpr uint8_t {name}[] = {{")
    for i in range(0, len(bits), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in bits[i : i + 24]) + ",")
    lines += ["};", ""]


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by tools/photos/bake_photos.py -- do not edit.",
        "",
        '#include "photos.hpp"',
        "",
        "namespace {",
        "",
    ]
    for photo in PHOTOS:
        mono, gray = bake(photo)
        lines.append(f"// {photo.credit}")
        lines.append(f"// {photo.url}")
        emit_array(lines, f"k{photo.name}", mono)
        emit_array(lines, f"k{photo.name}Gray", gray)
    lines.append("constexpr Bitmap kPhotos[] = {")
    for photo in PHOTOS:
        lines.append(f"    {{photos::kWidth, photos::kHeight, k{photo.name}}},")
    lines += ["};", "", "constexpr GrayBitmap kGrayPhotos[] = {"]
    for photo in PHOTOS:
        lines.append(f"    {{photos::kWidth, photos::kHeight, k{photo.name}Gray}},")
    lines += ["};", "", "}  // namespace", "", "namespace photos {", "",
              "const std::span<const Bitmap> kBuiltIn{kPhotos};",
              "const std::span<const GrayBitmap> kBuiltInGray{kGrayPhotos};", "", "}  // namespace photos", ""]
    (OUT_DIR / "default_photos.cpp").write_text("\n".join(lines), encoding="utf-8")

    header = f"""#pragma once

// Generated by tools/photos/bake_photos.py -- do not edit.

#include <span>

#include "canvas.hpp"

// Privacy mode's photos: the photo frame's size, and the built-in ones
// shown until the user uploads their own.
namespace photos {{

inline constexpr int kWidth = {WIDTH};
inline constexpr int kHeight = {HEIGHT};

// The same photos twice: dithered to black and white, and to four gray
// levels for panels with a 4-gray mode. Same order in both.
extern const std::span<const Bitmap> kBuiltIn;
extern const std::span<const GrayBitmap> kBuiltInGray;

}}  // namespace photos
"""
    (OUT_DIR / "photos.hpp").write_text(header, encoding="utf-8")
    (OUT_DIR / "CMakeLists.txt").write_text(
        'idf_component_register(SRCS "default_photos.cpp"\n'
        '                    INCLUDE_DIRS "."\n'
        "                    REQUIRES canvas)\n",
        encoding="utf-8",
    )
    size = len(PHOTOS) * HEIGHT * ((WIDTH + 7) // 8 + (WIDTH + 3) // 4)
    print(f"{len(PHOTOS)} photos, {size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
