#!/usr/bin/env python3
"""Bakes the built-in privacy-mode photos into components/photos/: each one
cropped to the photo frame, dithered to 1bpp and emitted as a Bitmap.

    ../font_subset/.venv/bin/python bake_photos.py

Sources are public-domain prints from Wikimedia Commons, downloaded into
.cache/ (gitignored) on first run with their SHA-256 pinned. Uploaded
photos go through the same steps in the browser (setup page), so keep the
two in step: fit-crop, autocontrast (1% cutoff), Atkinson dithering.
"""
import hashlib
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageOps

HERE = Path(__file__).resolve().parent
CACHE = HERE / ".cache"
OUT_DIR = HERE.parent.parent / "components" / "photos"

# Must match photos.hpp / the calendar view's photo frame.
WIDTH, HEIGHT = 730, 280


@dataclass
class Photo:
    name: str  # C++ symbol suffix
    url: str
    sha256: str
    center_y: float  # vertical crop position, 0 = top, 1 = bottom
    credit: str


PHOTOS = [
    Photo(
        "GreatWave",
        "https://upload.wikimedia.org/wikipedia/commons/a/a5/Tsunami_by_hokusai_19th_century.jpg",
        "30c170260de393f51bd592adacc6f0714b60f157c09744e9c5b6d46e6a613718",
        0.55,
        "Katsushika Hokusai, The Great Wave off Kanagawa (c. 1831), public domain",
    ),
    Photo(
        "RedFuji",
        "https://upload.wikimedia.org/wikipedia/commons/5/57/Red_Fuji_southern_wind_clear_morning.jpg",
        "6266cbb436f958b3197f6a048c3a738a7353eb4d6f37702970ee9feb689f47cd",
        0.42,
        "Katsushika Hokusai, Fine Wind, Clear Morning (c. 1831), public domain",
    ),
]


def fetch(photo):
    path = CACHE / Path(photo.url).name
    if not path.exists():
        CACHE.mkdir(exist_ok=True)
        print(f"downloading {photo.url}")
        request = urllib.request.Request(photo.url, headers={"User-Agent": "GlanceFirmware/1.0 (personal project)"})
        with urllib.request.urlopen(request) as response:
            path.write_bytes(response.read())
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != photo.sha256:
        raise SystemExit(f"{path.name} changed upstream (sha256 {digest}); review, then update the pin")
    return path


def atkinson(img):
    """1bpp rows (MSB first, 1 = white) via Atkinson dithering: 6/8 of the
    error spreads to nearby pixels, the rest is dropped, which keeps
    highlights and shadows clean on a 1-bit panel."""
    w, h = img.size
    px = [float(v) for v in img.tobytes()]
    rows = bytearray()
    for y in range(h):
        row = bytearray((w + 7) // 8)
        for x in range(w):
            i = y * w + x
            old = px[i]
            white = old >= 128
            if white:
                row[x // 8] |= 0x80 >> (x % 8)
            err = (old - (255.0 if white else 0.0)) / 8
            for dx, dy in ((1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)):
                xx, yy = x + dx, y + dy
                if 0 <= xx < w and yy < h:
                    px[yy * w + xx] += err
        rows += row
    return bytes(rows)


def bake(photo):
    img = Image.open(fetch(photo)).convert("L")
    img = ImageOps.fit(img, (WIDTH, HEIGHT), Image.LANCZOS, centering=(0.5, photo.center_y))
    return atkinson(ImageOps.autocontrast(img, cutoff=1))


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by tools/photos/bake_photos.py -- do not edit.",
        "",
        '#include "photos.hpp"',
        "",
        "namespace {",
        "",
    ]
    for photo in PHOTOS:
        bits = bake(photo)
        lines.append(f"// {photo.credit}")
        lines.append(f"// {photo.url}")
        lines.append(f"constexpr uint8_t k{photo.name}[] = {{")
        for i in range(0, len(bits), 24):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in bits[i : i + 24]) + ",")
        lines += ["};", ""]
    lines.append("constexpr Bitmap kPhotos[] = {")
    for photo in PHOTOS:
        lines.append(f"    {{photos::kWidth, photos::kHeight, k{photo.name}}},")
    lines += ["};", "", "}  // namespace", "", "namespace photos {", "", "const std::span<const Bitmap> kBuiltIn{kPhotos};",
              "", "}  // namespace photos", ""]
    (OUT_DIR / "default_photos.cpp").write_text("\n".join(lines), encoding="utf-8")

    header = f"""#pragma once

// Generated by tools/photos/bake_photos.py -- do not edit.

#include <span>

#include "canvas.hpp"

// Privacy mode's photos: the photo frame's size, and the built-in ones
// shown until the user uploads their own.
namespace photos {{

inline constexpr int kWidth = {WIDTH};
inline constexpr int kHeight = {HEIGHT};

extern const std::span<const Bitmap> kBuiltIn;

}}  // namespace photos
"""
    (OUT_DIR / "photos.hpp").write_text(header, encoding="utf-8")
    (OUT_DIR / "CMakeLists.txt").write_text(
        'idf_component_register(SRCS "default_photos.cpp"\n'
        '                    INCLUDE_DIRS "."\n'
        "                    REQUIRES canvas)\n",
        encoding="utf-8",
    )
    print(f"{len(PHOTOS)} photos, {len(PHOTOS) * HEIGHT * ((WIDTH + 7) // 8) / 1024:.0f} KB")


if __name__ == "__main__":
    main()
