#pragma once

#include <cstdint>
#include <span>

// Bitmap font as plain data. Every field is a span, so a Font looks the same
// whether its arrays are compiled into flash (generated by
// tools/font_subset/) or, later, loaded from a file at runtime -- the
// renderer never needs to know which.
//
// Generated arrays must be `const` at namespace scope so they land in flash
// (.rodata) instead of being copied into RAM at boot.

struct Glyph {
    uint32_t codepoint;
    uint32_t bitmapOffset;  // into Font::bitmaps
    uint16_t width;         // bitmap size in pixels
    uint16_t height;
    int16_t bearingX;  // bitmap's left edge relative to the pen position
    int16_t bearingY;  // bitmap's top edge above the baseline
    uint16_t advance;  // how far the pen moves after this glyph
};

struct Font {
    std::span<const Glyph> glyphs;     // sorted by codepoint
    std::span<const uint8_t> bitmaps;  // 1bpp, MSB-first, each row padded to a whole byte, 1 = ink
    uint16_t ascent;                   // baseline's distance below the line box's top
    uint16_t lineHeight;

    // nullptr if the font doesn't cover the codepoint.
    const Glyph* find(uint32_t codepoint) const;
};
