#pragma once

// Generated by tools/photos/bake_photos.py -- do not edit.

#include <span>

#include "canvas.hpp"

// Privacy mode's photos: the photo frame's size, and the built-in ones
// shown until the user uploads their own.
namespace photos {

inline constexpr int kWidth = 730;
inline constexpr int kHeight = 280;

extern const std::span<const Bitmap> kBuiltIn;

}  // namespace photos
