#pragma once

// Generated by tools/font_subset/font_subset.py -- do not edit.
// Noto Sans TC baked to 1bpp bitmaps; SIL Open Font License 1.1, see LICENSE-OFL.txt.

#include "font.hpp"

extern const Font kNotoSansTcBold30;  // event list
extern const Font kNotoSansTcBold40;  // year, weekday
extern const Font kNotoSansTcMedium50;  // month
extern const Font kNotoSansTcRegular100;  // day of month
extern const Font kNotoSansTcBold20;  // temperature, chance of rain
