#pragma once

// Generated by tools/icons/bake_icons.py -- do not edit.

#include "font.hpp"

// Weather icons as glyphs. Draw one with drawText; the pen position is
// the icon box's bottom-left corner (weather icons share a 101x80 box).
extern const Font kWeatherIcons;

namespace icons {
inline constexpr const char* kSunny = "\xEE\x80\x80";  // U+E000
inline constexpr const char* kPartlyCloudy = "\xEE\x80\x81";  // U+E001
inline constexpr const char* kCloudy = "\xEE\x80\x82";  // U+E002
inline constexpr const char* kWindy = "\xEE\x80\x83";  // U+E003
inline constexpr const char* kRainy = "\xEE\x80\x84";  // U+E004
inline constexpr const char* kRaindrop = "\xEE\x80\x85";  // U+E005
}  // namespace icons
